// todomvc/solid/src/TodoItem.jsx
import { Component } from 'solid-components'
import { r } from 'solid-js/dom'

import style from './TodoItem.css'

const TodoItem = (props, { element }) => (
  <>
    <style>{ style }</style>
    <li class={( props.checked ? 'completed' : '' )}>
      <input
        type="checkbox" checked={ props.checked }
        onInput={() => element.trigger('check', { detail: !props.checked })}
      />
      <label>
        <slot />
      </label>
      <button onClick={() => element.trigger('remove')}>x</button>
    </li>
  </>
);

Component('todo-item', { checked: false }, TodoItem);

// stencil/src/components/todo-item/todo-item.tsx
import { Component, Prop, Event, EventEmitter } from '@stencil/core';

@Component({
    tag: 'todo-item',
    styleUrl: 'todo-item.css'
    //shadow: true,
})
export class TodoItem {
    @Prop() checked: boolean;
    @Prop() text: string;
    @Prop() index: number;
    @Event() onTodoItemChecked: EventEmitter;
    @Event() onTodoItemRemove: EventEmitter;

    handleOnRemove = () => this.onTodoItemRemove.emit(this.index);
    handleOnChecked = () => this.onTodoItemChecked.emit(this.index);

    render() {
        return (
            <li class={this.checked ? 'completed' : ''}>
                <input type="checkbox" checked={this.checked} onChange={this.handleOnChecked} />
                <label>{this.text}</label>
                <button onClick={this.handleOnRemove}>x</button>
            </li>
        );
    }
}
