// todomvc/lit-element/js/my-todo.js
import { LitElement, html } from '../node_modules/lit-element/lit-element.js';
import { repeat } from '../node_modules/lit-html/directives/repeat.js';

let nextId = 0;

class MyTodo extends LitElement {
    static get properties() {
        return {
            list: { 
                type: Array
            }
        };
    }

    constructor() {
        super();
        this.list = [{ id: nextId++, text: 'my initial todo', checked: false }, { id: nextId++, text: 'Learn about Web Components', checked: true }];
    }

    render() {
        return html`
<style>
h1 {
    font-size: 100px;
    font-weight: 100;
    text-align: center;
    color: rgba(175, 47, 47, 0.15);
}

section {
    background: #fff;
    margin: 130px 0 40px 0;
    position: relative;
    box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2), 0 25px 50px 0 rgba(0, 0, 0, 0.1);
}

#list-container {
    margin: 0;
    padding: 0;
    list-style: none;
    border-top: 1px solid #e6e6e6;
}
</style>
<h1>Todos WC</h1>
<section>
    <todo-input @submit=${this.addItem}></todo-input>
    <ul id="list-container">
        ${repeat(
            this.list,
            item => item.id,
            (item, index) => html`
                <todo-item 
                    .text="${item.text}" 
                    .checked="${item.checked}" 
                    .index="${index}" 
                    @removed=${this.removeItem}
                    @checked=${this.toggleItem}>
                </todo-item>`)}
    </ul>
</section>`;
    }

    addItem(e) {
        this.list.splice(this.list.length, 0, { id: nextId++, text: e.detail, checked: false });
        this.requestUpdate();
    }

    removeItem(e) {
        this.list.splice(e.detail, 1);
        this.requestUpdate();
    }

    toggleItem(e) {
        const item = this.list[e.detail];
        item.checked = !item.checked;
        this.requestUpdate();
    }
}

window.customElements.define('my-todo', MyTodo);

// todomvc/svelte/src/my-todo.svelte
<svelte:options tag="my-todo"/>

<style>
    h1 {
        font-size: 90px;
        font-weight: 100;
        text-align: center;
        color: rgba(175, 47, 47, 0.15);
    }

    section {
        background: #fff;
        margin: 130px 0 40px 0;
        position: relative;
        box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2), 0 25px 50px 0 rgba(0, 0, 0, 0.1);
    }

    #list-container {
        margin: 0;
        padding: 0;
        list-style: none;
        border-top: 1px solid #e6e6e6;
    }
</style>

<script>
	let todoList = [{
            text: 'my initial todo',
            checked: false,
            id: 0
        },
        {
            text: 'Learn about Web Components',
            checked: true,
            id: 1
        }
    ];

    let input;

    import { onMount } from 'svelte';

    onMount(async () => {
		input = document.querySelector('my-todo').shadowRoot.querySelector('todo-input');
        console.log(input);

        input.addEventListener('createee', function (ev) {
            console.log('createee');
        });
	});

    console.log(todoList);

    function addItem(text) {
        console.log('addItem: ', text);
        const { todoList } = this.get();
        todoList.push({
            text,
            checked: false,
            id: todoList[todoList.length - 1].id + 1
        });
        this.set({
            todoList
        });
    }

    function removeItem(index) {
        console.log('removeItem: ', index);
        const { todoList } = this.get();
        todoList.splice(index, 1);
        this.set({
            todoList
        });
    }

    function toggleItem(item) {
        console.log('toggleItem: ', item);
        item.checked = !item.checked
        this.set({
            todoList: this.get().todoList
        });
    }
</script>

<div>
    <h1>Todos Svelte</h1>
    <section>
        <todo-input on:createee={addItem}></todo-input>
        <ul id="list-container">
            {#each todoList as todo, index (todo.id)}
                <todo-item text={todo.text} checked={todo.checked} on:toggle={toggleItem} on:remove={removeItem}></todo-item>
            {/each}
        </ul>
    </section>
</div>
