// todomvc/vue.js/src/my-todo.vue
<template>
  <div>
    <h1>Todos Vue</h1>
    <section>
      <todo-input @onnewtodo="add"></todo-input>
      <ul id="list-container">
        <todo-item v-for="item in itens" :key="item.value" :todo-checked="item.checked" :todo-text="item.text" @onremove="remove"></todo-item>
      </ul>
    </section>
  </div>
</template>

<script>
export default {
  name: "MyTodo",
  data() {
    return {
      itens: [
        { text: "my initial todo", checked: false },
        { text: "Learn about Web Components", checked: true }
      ]
    };
  },
  methods:{
    add(item){
      this.itens.push(item.detail[0])
    },
    remove(item){
      this.itens = this.itens.filter(e => e.text != item.detail[0])
    }
  }
};
</script>
 <style>
:host {
  display: block;
}

h1 {
  font-size: 80px;
  font-weight: 100;
  text-align: center;
  color: rgba(175, 47, 47, 0.15);
}

section {
  background: #fff;
  margin: 130px 0 40px 0;
  position: relative;
  box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2), 0 25px 50px 0 rgba(0, 0, 0, 0.1);
}

#list-container {
  margin: 0;
  padding: 0;
  list-style: none;
  border-top: 1px solid #e6e6e6;
}
</style>

// angular-elements/src/my-todo.ts
import {
    Component,
    ViewEncapsulation,
    ChangeDetectionStrategy
} from '@angular/core';

interface TodoItem {
    text: string;
    checked: boolean;
}

@Component({
    selector: 'my-todo',
    template: `
        <h1>Todos Angular Elements</h1>
        <section>
            <todo-input (onTodoInputSubmit)="todoInputSubmiHandler($event)"></todo-input>
            <todo-item
                *ngFor="let item of list; let i = index"
                [checked]="item.checked"
                [text]="item.text"
                [index]="i"
                (onTodoItemChecked)="todoItemCheckedHandler($event, i)"
                (onTodoItemRemove)="todoItemRemoveHandler($event, i)"
            ></todo-item>
        </section>
    `,
    styles: [`
        h1 {
            font-size: 55px;
            font-weight: 100;
            text-align: center;
            color: rgba(175, 47, 47, 0.15);
        }

        section {
            background: #fff;
            margin: 130px 0 40px 0;
            position: relative;
            box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2), 0 25px 50px 0 rgba(0, 0, 0, 0.1);
        }

        #list-container {
            margin: 0;
            padding: 0;
            list-style: none;
            border-top: 1px solid #e6e6e6;
        }
    `],
    changeDetection: ChangeDetectionStrategy.OnPush,
    encapsulation: ViewEncapsulation.Native
})
export class MyTodo {
    list: TodoItem[] = [
        { text: 'my initial todo', checked: false },
        { text: 'Learn about Web Components', checked: true }
    ];

    todoInputSubmiHandler(e) {
        this.list = [...this.list, { text: e, checked: false, }];
    }

    todoItemCheckedHandler(e, i) {
        const list = [...this.list];
        const item = list[i];
        list[i] = Object.assign({}, item, { checked: !item.checked });
        this.list = list;
    }

    todoItemRemoveHandler(e, i) {
        this.list = [...this.list.slice(0, i), ...this.list.slice(i + 1)];
    }
}
