// todomvc/stencil/src/components/todo-input/todo-input.tsx
import { h, Component, State, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'todo-input',
  styleUrl: 'todo-input.css',
  shadow: true
})
export class TodoInput {
  @Event() onTodoInputSubmit: EventEmitter;
  @State() value: string;

  handleOnSubmit = e => {
    e.preventDefault();
    if (!this.value) return;
    this.onTodoInputSubmit.emit(this.value);
    this.value = '';
  };

  handleInputChange = event => (this.value = event.target.value);

  render() {
    return (
      <form onSubmit={this.handleOnSubmit}>
        <input
          id="input-submit"
          value={this.value}
          type="text"
          placeholder="What needs to be done?"
          onInput={this.handleInputChange}
        />
      </form>
    );
  }
}

// todomvc/solid/src/TodoInput.jsx
import { Component } from 'solid-components';
import { createState } from 'solid-js';
import { r } from 'solid-js/dom';

import style from './TodoInput.css';

const TodoInput = (props, { element }) => {
  const [state, setState] = createState({ value: '' }),
    handleSubmit = e => {
      e.preventDefault();
      if (!state.value) return;
      element.trigger('create', { detail: state.value });
      setState({ value: '' });
    };

  return (<>
    <style>{ style }</style>
    <form onSubmit={ handleSubmit }>
      <input
        value={( state.value )}
        type="text"
        placeholder="What needs to be done?"
        onInput={({ target: { value } }) => setState({ value })}
      />
    </form>
  </>);
}

Component('todo-input', TodoInput);
