// todomvc/solid/src/MyTodo.jsx
import { Component } from 'solid-components';
import { createState } from 'solid-js';
import { r } from 'solid-js/dom';

import style from './MyTodo.css';
import './TodoInput';
import './TodoItem';

let uid = 1;
const MyTodo = () =>  {
  const [state, setState] = createState({ list: [
      { id: uid++, text: "my initial todo", checked: false },
      { id: uid++, text: "Learn about Web Components", checked: true }
    ] });

  return (<>
    <style>{ style }</style>
    <h1>Solid Todo</h1>
    <section>
      <todo-input onCreate={({ detail: text }) =>
        setState('list', l => [...l, { id: uid++, text, checked: false }])
      }/>
      <ul id="list-container">
        <$ each={ state.list }>{ item =>
          <todo-item
            model={ item.id }
            checked={( item.checked )}
            textContent={ item.text }
            onCheck={({ detail: checked }, id) => setState('list', state.list.findIndex(t => t.id === id), { checked })}
            onRemove={(e, id) => setState('list', l => l.filter(t => t.id !== id))}
          />
        }</$>
      </ul>
    </section>
  </>);
}

Component('my-todo', MyTodo);

// todomvc/stencil/src/components/my-todo/my-todo.tsx
import { Component, State, Listen } from '@stencil/core';

interface TodoItem {
  text: string;
  checked: boolean;
}

@Component({
  tag: 'my-todo',
  styleUrl: 'my-todo.css',
  shadow: true
})
export class MyTodo {
  @State() list: TodoItem[] = [
    { text: 'my initial todo', checked: false },
    { text: 'Learn about Web Components', checked: true }
  ];

  @Listen('onTodoInputSubmit')
  todoInputSubmiHandler(e: CustomEvent) {
    this.list = [...this.list, { text: e.detail, checked: false }];
  }

  @Listen('onTodoItemChecked')
  todoItemCheckedHandler(e: CustomEvent) {
    const list = [...this.list];
    const item = list[e.detail];
    list[e.detail] = Object.assign({}, item, { checked: !item.checked });
    this.list = list;
  }

  @Listen('onTodoItemRemove')
  todoItemRemoveHandler(e: CustomEvent) {
    this.list = [
      ...this.list.slice(0, e.detail),
      ...this.list.slice(e.detail + 1)
    ];
  }

  render() {
    return (
      <div>
        <h1>Todos Stencil</h1>
        <section>
          <todo-input />
          <ul id="list-container">
            {this.list.map((item, index) => (
              <todo-item
                checked={item.checked}
                text={item.text}
                index={index}
              />
            ))}
          </ul>
        </section>
      </div>
    );
  }
}
